const hobbies = {
  general: [
    "nature walks",
    "wine tasting",
    "snowboarding",
    "reading memoirs and biographies",
    "dance",
    "foraging",
    "outdoor movie nights",
    "foil surfing",
    "tattoo design",
    "making metal jewelry",
    "interior painting",
    "wakeboarding",
    "water skiing",
    "baking",
    "ice skating",
    "tree climbing",
    "yoga",
    "caving",
    "quilting",
    "solar observing",
    "dancing",
    "lego building",
    "martial arts",
    "dogsledding",
    "bird fluorescence",
    "competitive programming",
    "epsom salts",
    "christmas lights",
    "i packing",
    "ecology",
    "tai chi",
    "creative writing",
    "fountain penning",
    "cheerleading",
    "landscape painting",
    "hula hooping",
    "laughing",
    "social dancing",
    "urban hiking",
    "beadwork",
    "mandala painting",
    "mindfulness",
    "skip rope tricks",
    "jamming",
    "sprint running",
    "spellcheck",
    "french cooking",
    "costume design",
    "flamenco",
    "volunteering",
    "handstand practice",
    "language exchange",
    "graffiti art",
    "model building",
    "beatboxing",
    "fire spinning",
    "creative painting",
    "bean crafting",
    "costume making",
    "telescope building",
    "fencing",
    "candle dipping",
    "poker",
    "rocketry",
    "synchronized swimming",
    "mathematics exploration",
    "antique coin collecting",
    "illustration",
    "magnet collecting",
    "bottle cap collecting",
    "quilting",
    "armor building",
    "watercolor painting",
    "dodgeball",
    "digital painting",
    "stock trading",
    "taxidermy",
    "karaoke",
    "comic book writing",
    "urban exploring",
    "pet photography",
    "knot tying",
    "archaeology",
    "concert photography",
    "coffee roasting",
    "brochure design",
    "stamp collecting",
    "gardening",
    "beekeeping",
    "diving",
    "learning languages",
    "fact checking",
    "writing",
    "flower pressing",
    "model trains",
    "treasure hunting",
    "policy reading",
    "philosophy",
    "lego building",
    "origami",
    "birding",
    "mechanical repair",
    "moon gazing",
    "kayaking",
    "marathon running",
    "camping",
    "paleontology",
    "narrative writing",
    "psychedelic journaling",
    "zumba",
    "drone photography",
    "castlego building",
    "calligraphy",
    "astronomy",
    "electronics repair",
    "sculpting",
    "writing",
    "woodworking",
    "puzzles",
    "permaculture",
    "electronic music production",
    "learning coding",
    "dragon boat racing",
    "collecting rocks",
    "collecting coins",
    "collecting vinyl",
    "collecting stamps",
    "collecting teacups",
    "model rocketry",
    "computer programming",
    "volunteer teaching",
    "urban photography",
    "robotics",
    "public speaking",
    "piano playing",
    "quilting",
    "hiking",
    "gardening",
    "bridge",
    "cryptography",
    "stargazing",
    "meditation",
    "origami",
    "painting",
    "knitting",
    "poker",
    "kayaking",
    "football",
    "chess",
    "gardening",
    "birdwatching",
    "fencing",
    "swimming",
    "photography",
    "writing poetry",
    "guitar",
    "photography",
    "camping",
    "kitesurfing",
    "surfing",
    "bird watching",
    "soccer",
    "mountain biking",
    "parkour",
    "chemistry experiments",
    "model airplanes",
    "charity fundraising",
    "tattoo design",
    "skateboarding",
    "journalism",
    "astronomy",
    "calls and ladders",
    "remote control car racing",
    "making soap",
    "science experiments",
    "volleyball",
    "soccer",
    "rugby",
    "skating",
    "reading",
    "volunteering",
    "digital art",
    "calligraphy",
    "photography",
    "dancing",
    "film making",
    "coin collecting",
    "book reading",
    "drumming",
    "meme collecting",
    "karaoke",
    "jogging",
    "anime",
    "writing short stories",
    "drawing",
    "gardening",
    "yoga",
    "cooking",
    "fishing",
    "baking",
    "weight lifting",
    "handicrafts",
    "crafting",
    "whale watching",
    "skydiving",
    "astronomy",
    "meditation",
    "woodworking",
    "tailoring",
    "reading",
    "writing",
    "reading",
    "painting",
    "football",
    "soccer",
    "yoga",
    "coding",
    "cooking",
    "writing",
    "birdwatching",
    "meeting people",
    "scrapbooking",
    "drawing",
    "knitting",
    "crocheting",
    "traveling",
    "job seeking",
    "learning",
    "memoir writing",
    "content creation",
    "fashion design",
    "brewing",
    "brewing beer",
    "making wine",
  ],
  sports_and_outdoors: [
    "letterboxing",
    "motorcycling",
    "outdoor sketching",
    "competitor aikido",
    "hike scenes",
    "escaperoom puzzles",
    "fieldhockey",
    "football",
    "sunset watching",
    "softball",
    "mountain climbing",
    "ice hockey",
    "figure skating",
    "skydiving",
    "parkour",
    "lacrosse",
    "goalball",
    "rugby",
    "bouncing balls",
    "basketball",
    "snowboarding",
    "trampoline jump",
    "hiking",
    "skateboarding",
    "crossfit",
    "fencing",
    "taekwondo",
    "capoeira",
    "tae kwon do",
    "orienteering",
    "rafting",
    "american football",
    "synchronized swimming",
    "hula hooping",
    "pilates",
    "sailing",
    "whitewater rafting",
    "handball",
    "darts",
    "badminton",
    "surfing",
    "flag football",
    "boxing",
    "rock climbing",
    "volleyball",
    "ultimate frizbee",
    "games of dodge",
    "golfing",
    "animal training",
    "ice climbing",
    "orienteering races",
    "archery",
    "outdoor boot camps",
    "hula hooping",
    "polo",
    "marathon running",
    "wakeboarding",
    "fencing",
    "zephyr sailing",
    "snowmobile riding",
    "dragon boat racing",
    "bmx",
    "taichi",
    "curling",
    "surfing",
    "gps tracking",
    "parkour",
    "skydiving",
    "paintball",
    "hang gliding",
    "frisbee",
    "cross country skiing",
    "yoga",
    "ultimate frisbee",
    "running",
    "cardio",
    "karate",
    "hiking",
    "floorball",
    "soccer",
    "sumo wrestling",
    "mountain biking",
    "hiking",
    "bouldering",
    "snowboarding",
    "bobsledding",
    "hockey",
    "volleyball",
    "baseball",
    "soccer",
    "tennis",
    "martial arts",
    "skateboarding",
    "slam ball",
    "weightlifting",
    "parkour",
    "taekwondo",
    "softball",
    "longboarding",
    "bungee jumping",
    "crossfit",
    "rock climbing",
    "archery",
    "rollerblading",
    "standup paddleboarding",
    "kayaking",
    "ice skating",
    "boxing",
    "picnicking",
    "cheerleading",
    "goalball",
  ],
  education: [
    "blogging",
    "free college classes",
    "history research",
    "cryptography",
    "science experiments",
    "photography",
    "mathematics exploration",
    "biology study",
    "robotics",
    "philosophy discussions",
    "public speaking",
    "language learning",
    "physics experiments",
    "genealogy",
    "election forecasting",
    "reading",
    "studying film",
    "learning languages",
    "meeting people",
    "fantasy sports",
    "watching movies",
    "online research",
    "learning",
    "card games",
    "internet research",
    "robotics club",
    "theater",
    "seminars",
    "history",
    "science",
    "technology",
    "sociology study",
    "philosophy",
    "anthropology",
    "linguistics",
    "economics",
    "art history",
  ],
  collection: [
    "action figures",
    "baseball cards",
    "beer cans",
    "magnet collecting",
    "coin collecting",
    "button collecting",
    "souvenir collecting",
    "glassware collecting",
    "metal collecting",
    "rock collecting",
    "postcard collecting",
    "photograph collecting",
    "artifact collecting",
    "antique collecting",
    "album collecting",
    "candy collecting",
    "comic book collecting",
    "mineral collecting",
    "coin collecting",
    "stamp collecting",
    "action figure collecting",
    "bottle collecting",
    "game cards collecting",
    "toy collecting",
    "matchbox collecting",
    "beer label collecting",
    "tattoo art",
    "shell collecting",
    "puzzle collecting",
    "rare books",
    "water collecting",
    "holograph collecting",
    "fan memorabilia",
    "antique bookends",
    "antique buttons",
    "antique furniture",
    "antique cameras",
    "antique maps",
    "antique puzzles",
    "antique dolls",
    "pet stone collecting",
    "coin collecting",
    "stamp collecting",
    "snuff box collecting",
    "chess piece collecting",
    "antique clock collecting",
    "pearl collecting",
    "denim jacket collecting",
    "antique keys collecting",
    "button collecting",
    "decoy collecting",
    "art collecting",
    "quilting",
    "matchbox collecting",
  ],
  competition: [
    "bingo",
    "board games",
    "fantasy sports",
    "speedcubing",
    "bridge",
    "trivia",
    "video games",
    "card games",
    "jigsaw puzzles",
    "crossword puzzles",
    "speedcubing",
    "poker",
    "escape rooms",
    "mahjong",
    "role playing games",
    "cup stacking",
    "esports",
    "debate",
    "cup stacking",
    "rubiks cube",
    "poker",
    "bridge",
    "quiz bowl",
    "karaoke",
    "memory competitions",
    "trivia night",
    "speed sudoku",
    "marriage proposal planning",
    "beer drinking contest",
    "darts",
    "euchre",
    "memory championship",
    "esports",
    "quiz",
    "poker",
  ],
  observation: [
    "stargazing",
    "birdwatching",
    "people watching",
    "cloud watching",
    "trainspotting",
    "plane spotting",
    "satellite watching",
    "storm chasing",
    "volcano watching",
    "sunrise watching",
    "sunset watching",
    "wildlife observation",
    "whale watching",
    "butterfly watching",
    "leaf peeping",
    "moth watching",
    "moon watching",
    "meteor shower viewing",
    "galaxy viewing",
    "kite watching",
    "squirrel watching",
    "kite appreciation",
    "leaf appreciation",
    "digital cloud watching",
    "object photography",
    "mountain viewing",
  ],
};

export default function searchEngineHobbie(
  category:
    | "general"
    | "sports_and_outdoors"
    | "education"
    | "collection"
    | "competition"
    | "observation",
  query: string,
): string[] {
  const list = hobbies[category] || [];

  if (!query) return list;

  const filtered = hobbies[category].filter((item) =>
    item.toLowerCase().includes(query.toLowerCase()),
  );

  const formatted = filtered.map(
    (item) => item.charAt(0).toUpperCase() + item.slice(1),
  );

  return formatted;
}
