const hobbies = {
  general: [
    "3d printing",
    "3d printing projects",
    "accordion playing",
    "acroyoga",
    "acting",
    "amateur radio",
    "ancient mythology study",
    "animal rescue volunteering",
    "animated film festivals",
    "animé watching",
    "aquascaping",
    "architecture modeling",
    "art activism",
    "art collecting",
    "art history study",
    "astro-photography",
    "astrology",
    "astronomy",
    "at-home exercise",
    "audio production",
    "autobiography writing",
    "auto detailing",
    "autocross driving",
    "aviation",
    "ax throwing",
    "backgammon",
    "backpacking",
    "bagpipe playing",
    "baking",
    "ballroom dancing",
    "barbering",
    "barista work",
    "bartending",
    "baseball card collecting",
    "baseball",
    "basketball",
    "bathbomb crafting",
    "beachcombing",
    "beadwork",
    "beatboxing",
    "beer brewing",
    "beer tasting",
    "bell ringing",
    "bento box cooking",
    "bird feeding",
    "bird watching",
    "birding",
    "blacksmithing",
    "blogging",
    "bonsai cultivation",
    "bonsai gardening",
    "book discussion club",
    "book restoration",
    "bookbinding",
    "bookshelf arranging",
    "bootcamp workouts",
    "bouldering",
    "bowling",
    "braiding hair",
    "breakdancing",
    "bricklaying",
    "bridge",
    "brochure design",
    "bungee jumping",
    "calligraphy",
    "camera collecting",
    "camping",
    "canine training",
    "candle making",
    "candle decoration",
    "car spotting",
    "car restoration",
    "car racing",
    "car tuning",
    "card games",
    "cardistry",
    "caregiving",
    "carousel riding",
    "carpentry",
    "cassette tape collecting",
    "cello playing",
    "ceramic painting",
    "ceramics",
    "chainsaw carving",
    "challenge coin collecting",
    "chamber music",
    "champaign tasting",
    "cheerleading",
    "chess",
    "chiseling",
    "cinematography",
    "citizen science",
    "clay shooting",
    "cleaning",
    "climbing",
    "clothing design",
    "clothespin crafting",
    "club dancing",
    "coin collecting",
    "coins",
    "coloring",
    "comic creation",
    "comic book collecting",
    "community activism",
    "community gardening",
    "concert going",
    "conlanging",
    "construction model building",
    "cooking",
    "costume design",
    "couch surfing",
    "couch to 5k program",
    "couverture chocolate tasting",
    "covfefe tasting",
    "cryptocurrency trading",
    "cryptography",
    "cultural anthropology study",
    "curling",
    "cycling",
    "dance choreography",
    "dance",
    "data visualization",
    "debate",
    "debutante ball",
    "decorating",
    "dedovitch",
    "deep sea diving",
    "dendrology",
    "designing video games",
    "digital arts",
    "digital painting",
    "digital printing",
    "dog obedience training",
    "dollhouse building",
    "doll collecting",
    "doodling",
    "do it yourself",
    "double dutch",
    "dowsing",
    "drama",
    "dramaturgy",
    "drawings",
    "drifting (motorsport)",
    "drone building",
    "drone photography",
    "drone racing",
    "drum circle",
    "drumming",
    "drums playing",
    "dvd collecting",
    "eating contests",
    "educational travel",
    "educational videos",
    "electronics",
    "electronics repair",
    "electronics tinkering",
    "embroidery",
    "energy work",
    "engineering projects",
    "entrepreneurship",
    "epigraphy",
    "escape room solving",
    "ethnic cooking",
    "event planning",
    "excavation",
    "executive coaching",
    "exhibition visiting",
    "experience design",
    "extreme ironing",
    "face painting",
    "fairy gardens",
    "family history research",
    "fantasy sports",
    "farmers market shopping",
    "farmhouse cooking",
    "fencing",
    "figure skating",
    "filmmaking",
    "finance games",
    "fingerboarding",
    "firefighting training",
    "fire pit building",
    "fireworks viewing",
    "flag football",
    "flamenco dancing",
    "flash mob dancing",
    "floorball",
    "flower pressing",
    "fly tying",
    "foam sword fighting",
    "foraging",
    "foreign language learning",
    "formatting guides",
    "fort building",
    "found object art",
    "found footage filmmaking",
    "free diving",
    "free writing",
    "freestyle football",
    "frisbee golf",
    "fruit picking",
    "fundraising",
    "futurism study",
    "gabber music",
    "gardening",
    "genealogy",
    "geocaching",
    "gemstone collecting",
    "geology",
    "ghost hunting",
    "gift wrapping",
    "glassblowing",
    "glider piloting",
    "gluing",
    "go kart racing",
    "gold prospecting",
    "golfing",
    "guitar playing",
    "hacking",
    "hairstyling",
    "ham radio",
    "hand sewing",
    "handwriting",
    "handball",
    "handicrafts",
    "hang gliding",
    "harmony singing",
    "hay bale sculpture",
    "headbutting (sport)",
    "hedge maze design",
    "helicopter piloting",
    "hello neighbor living",
    "high-power rocketry",
    "high-intensity interval training",
    "historical reenactment",
    "home bartending",
    "home brews",
    "home decorating",
    "home improvement",
    "homeopathy study",
    "hoop dancing",
    "hope chest collecting",
    "horse breeding",
    "horse racing",
    "horseback riding",
    "horticulture",
    "hostelling",
    "houseplant care",
    "house renovation",
    "humanitarian work",
    "hula hooping",
    "hydroponics",
    "ice fishing",
    "ice skating",
    "illustration",
    "immersion language study",
    "impact assessment",
    "indoor skydiving",
    "industrial design",
    "infographics design",
    "instrument restoration",
    "instrument playing",
    "international travel",
    "internet memes",
    "internet puzzles",
    "interviewing people",
    "inventing",
    "irish dancing",
    "jazz appreciation",
    "jet skiing",
    "jigsaw puzzles",
    "joint rolling competitions",
    "journalism",
    "journaling",
    "juggling",
    "kabaddi",
    "kaleidoscope making",
    "karate",
    "keepy uppies",
    "kayaking",
    "kendo",
    "kenpō",
    "key collecting",
    "kiteboarding",
    "kite flying",
    "knot tying",
    "knitting",
    "knowledge competitions",
    "kongfu",
    "korean barbecue cooking",
    "kosher baking",
    "krav maga",
    "kumihimo braiding",
    "lacemaking",
    "lacrosse",
    "lake swimming",
    "lanyard making",
    "language clubs",
    "latin dancing",
    "lava lamp collecting",
    "learning about history",
    "learning magic tricks",
    "learning new languages",
    "lego building",
    "letter writing",
    "letterboxing",
    "letting letters",
    "leukemia awareness campaigning",
    "life coaching",
    "lifeguarding training",
    "listening to audiobooks",
    "listening to music",
    "listening to podcasts",
    "live action role-playing",
    "lock picking",
    "macrame",
    "machine learning",
    "macrame",
    "magic tricks",
    "makeup artistry",
    "male cheerleading",
    "manga reading",
    "manicure design",
    "manuscript study",
    "marathon running",
    "marching band",
    "marine biology study",
    "marksmanship",
    "martial arts",
    "martial arts: aikido",
    "martial arts: karate",
    "martial arts: judo",
    "martial arts: jiu jitsu",
    "martial arts: krav maga",
    "martial arts: kung fu",
    "martial arts: taekwondo",
    "marzipan sculpting",
    "massage",
    "match photography",
    "math exploration",
    "mathematics",
    "mechanical repair",
    "mechanics",
    "meditation",
    "memory training",
    "metal crafting",
    "metalworking",
    "meteor watching",
    "meteorology",
    "microbiology",
    "miniature painting",
    "mineral collecting",
    "mobile photography",
    "model aircraft building",
    "model building",
    "model railroading",
    "model rocketry",
    "moderating forums",
    "motorcycling",
    "mountain biking",
    "mountain climbing",
    "mountaineering",
    "movement therapy",
    "movie filmmaking",
    "movie making",
    "movie watching",
    "motor sports",
    "mtg collecting",
    "museum visiting",
    "music appreciation",
    "music festivals attending",
    "music production",
    "music theory",
    "mustache styling",
    "mycology",
    "narwhal watching",
    "natural dyeing",
    "network engineering",
    "news watching",
    "norwegian woodcraft",
    "nova watching",
    "nutcracking",
    "numismatics",
    "object photography",
    "obsidian collecting",
    "oceanography",
    "orchestra participation",
    "origami",
    "ostrich racing",
    "our planet preservation",
    "outdoor boot camps",
    "outdoor yoga",
    "painting",
    "palace tours",
    "park design",
    "parkour",
    "party planning",
    "passion projects",
    "passport collecting",
    "pasteboard craft",
    "pasta making",
    "pendant crafting",
    "perfume making",
    "pet photography",
    "pet training",
    "petroduinos",
    "pfaff collecting",
    "philately",
    "philosophy",
    "photo editing",
    "photography",
    "photography club",
    "physics experiments",
    "piano playing",
    "pin collecting",
    "pioneer camping",
    "pipeline surveying",
    "planetarium visits",
    "plastic art",
    "playwriting",
    "plush toy making",
    "poems writing",
    "poetry",
    "polynesian dancing",
    "pool",
    "pop figure collecting",
    "pool making",
    "popsicle stick crafts",
    "pocket watch collecting",
    "poetry reading",
    "pok\u00e9mon training",
    "pony riding",
    "popular science reading",
    "porcelain doll collecting",
    "poroscaping",
    "poster design",
    "power gardening",
    "powerlifting",
    "prayer",
    "precious metal detecting",
    "premium tea tasting",
    "princess playing",
    "printing circuit boards",
    "prison penpal",
    "professional volunteering",
    "programmable robotics",
    "programming",
    "public speaking",
    "puppet making",
    "puppetry",
    "puzzles",
    "puzzle creation",
    "quarter racing",
    "quantum physics",
    "quilting",
    "radio controlled models",
    "railfanning",
    "rapping",
    "rare book collecting",
    "ratio puzzles",
    "reading fiction",
    "reading magazines",
    "reading memoirs and biographies",
    "reading manga",
    "reading non-fiction",
    "reading newspapers",
    "reading poetry",
    "reading short stories",
    "reading strategy guides",
    "real estate investing",
    "record collecting",
    "recording music",
    "redoing furniture",
    "reiki",
    "renewable energy projects",
    "remote control cars",
    "repairing items",
    "research",
    "resin art",
    "retail arbitrage",
    "retrowave music",
    "riddle solving",
    "role playing games",
    "robotics",
    "rock painting",
    "rock balancing",
    "rope skipping",
    "rug hooking",
    "rugby",
    "running",
    "russian language study",
    "rustic woodworking",
    "sailing",
    "samba dancing",
    "samurai studying",
    "sand art",
    "sandcastle building",
    "saxophone playing",
    "scrapbooking",
    "scuba diving",
    "sculpting",
    "seashell collecting",
    "seasonal decorating",
    "scouting",
    "screwdriver collection",
    "sewing",
    "shadow puppetry",
    "shibari",
    "skateboarding",
    "sketch comedy",
    "sketching",
    "skipping rope",
    "slash puzzles",
    "sleight of hand",
    "slacklining",
    "sled dog racing",
    "sledding",
    "snail racing",
    "snake charming",
    "snorkeling",
    "snowboarding",
    "snowmobiling",
    "snowshoeing",
    "soccer",
    "soccer juggling",
    "social dancing",
    "social media curation",
    "socializing",
    "sock puppet making",
    "sodoku",
    "software development",
    "solar observing",
    "solar panel installation",
    "solving cryptograms",
    "solving jigsaw puzzles",
    "spanish cooking",
    "speaker collecting",
    "spider raising",
    "spider farming",
    "spycraft",
    "square dancing",
    "stamp collecting",
    "star gazing",
    "stickball",
    "still-life photography",
    "stitching",
    "stock trading",
    "stop motion animation",
    "storytelling",
    "strength training",
    "street painting",
    "strings collection",
    "study of etymology",
    "submarine spotting",
    "sun gazing",
    "sunrise watching",
    "sunset watching",
    "sunspot watching",
    "survivalism",
    "swimming",
    "sword making",
    "symphony watching",
    "synchronized swimming",
    "tabletop games",
    "tai chi",
    "tai chi chuan",
    "taekwondo",
    "talk radio listening",
    "tattoo design",
    "tattooing",
    "taxidermy",
    "teacup collecting",
    "team marching",
    "team sports",
    "technical drawing",
    "television watching",
    "teleportation attempts",
    "temporal meditation",
    "tent pitching",
    "theatre",
    "thumb wrestling",
    "tie-dye making",
    "timber framing",
    "time capsule making",
    "tinkering",
    "tiny house building",
    "tool collecting",
    "topiary",
    "torus untying",
    "touch typing",
    "tour skating",
    "touring historical sites",
    "tower building",
    "track walking",
    "trade fair visiting",
    "trail hiking",
    "travel writing",
    "tree climbing",
    "treehouse building",
    "trick horse riding",
    "trick photography",
    "trombone playing",
    "trouble-shooting puzzles",
    "truck restoration",
    "trumpet playing",
    "ukulele playing",
    "ultimate frisbee",
    "urban climbing",
    "urban farming",
    "urban gardening",
    "urban exploration",
    "user interface design",
    "uv photography",
    "vacation planning",
    "vaccine education",
    "vehicle restoration",
    "vegan cooking",
    "vegetable gardening",
    "venture capital games",
    "vexillology",
    "videography",
    "video editing",
    "video game developing",
    "video gaming",
    "videography",
    "violin playing",
    "video blogging",
    "video diorama making",
    "virtual reality art",
    "virtual reality gaming",
    "vlogging",
    "volcano observation",
    "volunteer mentoring",
    "volunteering",
    "wall painting",
    "wargaming",
    "washi tape crafting",
    "watch making",
    "watching documentaries",
    "watching movies",
    "watching sports games",
    "watching television",
    "water polo",
    "waterskiing",
    "weather photography",
    "weather watching",
    "weightlifting",
    "welder",
    "whale watching",
    "wine tasting",
    "wire wrapping",
    "wizarding (magical practice)",
    "word searches",
    "word puzzles",
    "working out",
    "worldbuilding",
    "writing",
    "writing music",
    "xylophone playing",
    "yoga",
    "yo-yoing",
    "yodeling",
    "zumba dancing",
  ],
  sports_and_outdoors: [
    "aerial hoop",
    "aerial silks",
    "cricket",
    "air sports",
    "airsoft",
    "air hockey",
    "airsoft",
    "amateur geology",
    "amusement park visiting",
    "archery",
    "aerospace",
    "auditioning (music)",
    "backpacking",
    "badminton",
    "balance boarding",
    "baseball",
    "basketball",
    "beach volleyball",
    "beachcombing",
    "base jumping",
    "beekeeping",
    "billiards",
    "birdwatching",
    "bmx",
    "board sports",
    "bodyboarding",
    "bodybuilding",
    "bobsledding",
    "boxing",
    "bungee jumping",
    "bus riding",
    "butterfly watching",
    "camping",
    "canoeing",
    "canoe camping",
    "canyoning",
    "car racing",
    "car tuning",
    "cars restoration",
    "cycling",
    "curling",
    "dairy farming",
    "darts",
    "disc golf",
    "disc throwing",
    "dog agility",
    "dog training",
    "dodgeball",
    "drone racing",
    "drifting",
    "drum corps",
    "drum training",
    "dune bashing",
    "election forecasting",
    "equine vaulting",
    "escalade (climbing)",
    "e-sports",
    "exchange student travel",
    "extreme sports",
    "family hiking",
    "farming",
    "field hockey",
    "flag football",
    "fly fishing",
    "football",
    "foraging",
    "fort building",
    "fossil hunting",
    "fouling (yachting)",
    "free diving",
    "freestyle skiing",
    "friendship bracelet swaps",
    "frisbee golf",
    "frisbee throwing",
    "fruit picking",
    "garden planning",
    "gardening",
    "gliding",
    "goalball",
    "gold prospecting",
    "golfing",
    "groundhopping",
    "gymnastics",
    "hang gliding",
    "handball",
    "hard enduro",
    "high-intensity interval training",
    "hiking",
    "hobby horsing",
    "hobby tunneling",
    "hooping",
    "horseback riding",
    "horseshoes",
    "hovercraft building",
    "hula hooping",
    "ice boating",
    "ice climbing",
    "ice hockey",
    "ice skating",
    "inline skating",
    "jet skiing",
    "jump rope tricks",
    "juggling",
    "karate",
    "kart racing",
    "kite flying",
    "kite surfing",
    "kitesurfing",
    "kung fu",
    "lacrosse",
    "laser tag",
    "lawn bowling",
    "longboarding",
    "lyft driving",
    "magnet fishing",
    "mixed martial arts",
    "motocross",
    "motorcycling",
    "mountain biking",
    "mountain climbing",
    "mountaineering",
    "mountain sledding",
    "museum visiting",
    "mushroom hunting",
    "netball",
    "ninja warrior training",
    "non-violent protest preparation",
    "noodling",
    "orienteering",
    "outdoor boot camps",
    "paragliding",
    "parkour",
    "parachuting",
    "pickleball",
    "pilates",
    "pit bike racing",
    "plogging",
    "pole dancing",
    "polocrosse",
    "powerlifting",
    "racing (cars)",
    "rafting",
    "railway journeys",
    "railway modelling",
    "rally racing",
    "randon\u00e9e",
    "reading speed competitions",
    "remote control car racing",
    "road biking",
    "rock climbing",
    "rock tumbling",
    "roller derby",
    "roller skating",
    "rollerblading",
    "rowing",
    "rugby",
    "sailing",
    "sand boarding",
    "sand art",
    "scoring (sports)",
    "scouting",
    "scrimmaging",
    "scuba diving",
    "sculling",
    "sea kayaking",
    "seashell hunting",
    "scootering",
    "scouting games",
    "scrabble tournaments",
    "segment chasing (cycling)",
    "shooting",
    "shopping",
    "sightseeing tours",
    "silver smithing",
    "skateboarding",
    "skiing",
    "skimboarding",
    "skydiving",
    "slacklining",
    "sledgehammer chopping",
    "sled dog racing",
    "sledding",
    "snooker",
    "snowboarding",
    "snowmobiling",
    "snowshoeing",
    "soccer (football)",
    "soccer juggling",
    "softball",
    "solo travel",
    "spear throwing",
    "spelunking",
    "speed skating",
    "sport stacking",
    "sports fan clubs",
    "squash",
    "stable riding",
    "stationary bike racing",
    "steeplechase",
    "stone skipping",
    "street luge",
    "street workout",
    "strength training",
    "strike breaking",
    "sun gazing",
    "surfing",
    "swimming",
    "synchronized swimming",
    "table football",
    "table tennis",
    "tai chi",
    "target shooting",
    "taxidermy",
    "team sports",
    "tea farming",
    "telemark skiing",
    "tetherball",
    "thru-hiking",
    "timber framing",
    "tin can boat racing",
    "torpedo building",
    "tour skating",
    "tourism",
    "trail running",
    "training pets",
    "trampoline jumping",
    "triathlon",
    "tug of war",
    "ultimate frisbee",
    "underwater hockey",
    "urban exploration",
    "urban gardening",
    "urban knitting",
    "vacation planning",
    "volunteer firefighting",
    "volunteer coaching",
    "volunteering",
    "volleyball",
    "volleyball coaching",
    "wagon building",
    "wakeboarding",
    "walking",
    "water parks visiting",
    "water polo",
    "water skiing",
    "welding",
    "wheel throwing (pottery)",
    "windsurfing",
    "winter camping",
    "wolf watching",
    "wood carving",
    "woodworking",
    "world building",
    "world record attempts",
    "wrestling",
    "writing (speedwriting)",
    "yoga",
    "yoga retreats",
  ],
  education: [
    "archaeology",
    "asterology",
    "astronomy",
    "animation",
    "aerospace",
    "aquaculture",
    "art history",
    "astronautics",
    "audiology",
    "business",
    "biology",
    "botany",
    "cinematography study",
    "computer science",
    "cryptography courses",
    "culture studies",
    "culinary science",
    "cryptography",
    "fashion studies",
    "foreign language learning",
    "genealogy",
    "geography",
    "genetics",
    "history",
    "homeschooling",
    "horticulture",
    "intellectual discussion",
    "journalism study",
    "linguistics",
    "literature",
    "mathematics",
    "medical science",
    "meteorology",
    "microbiology",
    "mycology",
    "neuroscience",
    "paleontology",
    "philosophy",
    "physics",
    "policy reading",
    "political science",
    "psychology",
    "railway studies",
    "reading",
    "research",
    "sociology",
    "story writing",
    "theater studies",
    "teaching",
    "technology education",
    "theology",
    "urban planning",
    "web design",
    "zoology",
    "election forecasting",
    "stock market analysis",
  ],
  collection: [
    "action figures",
    "advertising signs",
    "anime figurines",
    "antique antiques",
    "antique bells",
    "antique bookends",
    "antique books",
    "antique buttons",
    "antique cameras",
    "antique chairs",
    "antique dishware",
    "antique dolls",
    "antique dollhouse furniture",
    "antique fans",
    "antique fishing lures",
    "antique furniture",
    "antique glass bottles",
    "antique gloves",
    "antique hat pins",
    "antique jewelry",
    "antique keys",
    "antique locks",
    "antique medical instruments",
    "antique microscopes",
    "antique photo albums",
    "antique postcards",
    "antique puzzles",
    "antique radios",
    "antique rugs",
    "antique silver spoons",
    "antique silverware",
    "antique swords",
    "antique tapestries",
    "antique tea sets",
    "antique tools",
    "antique toy cars",
    "antique trunks",
    "antique typewriters",
    "art pieces",
    "autographs",
    "band merchandise",
    "baseball cards",
    "beer cans",
    "book collecting",
    "books",
    "bottle caps",
    "brand merchandise",
    "bugs and insects",
    "children's books",
    "clocks and watches",
    "coca-cola memorabilia",
    "coins",
    "comic books",
    "concert tickets",
    "cooking utensils collecting",
    "crystals",
    "cups and glassware",
    "depression glass",
    "disneyana",
    "dolls",
    "feathers",
    "festival merchandise",
    "first editions",
    "fountain pens",
    "gemstones",
    "historical documents",
    "jersey collecting",
    "jewelry collecting",
    "keychains",
    "lego sets",
    "license plates",
    "lighters",
    "manga",
    "manuscripts",
    "matchbox cars",
    "meteorites",
    "military memorabilia",
    "miniatures",
    "movie memorabilia",
    "movie props",
    "old maps",
    "old postcards",
    "old photographs",
    "old maps",
    "old records",
    "old stamps",
    "perfume bottles",
    "pez dispensers",
    "photographs",
    "pinball machines",
    "postcards",
    "posters",
    "prismacolor pencils",
    "prizes",
    "records",
    "rare books",
    "realist painting",
    "religious artifacts",
    "soda bottles",
    "seashells",
    "snack packaging",
    "sneakers",
    "stamps",
    "stickers",
    "teacups",
    "teapots",
    "teddy bears",
    "ticket stubs",
    "toys",
    "trading cards",
    "video games",
    "vintage advertising",
    "vintage board games",
    "vintage buttons",
    "vintage cameras",
    "vintage clothing",
    "vintage hats",
    "vintage jewelry",
    "vintage logos",
    "vintage magazines",
    "vintage postcards",
    "vintage posters",
    "vintage sewing machines",
    "vintage sheet music",
    "vintage watches",
    "vinyl records",
    "wine bottles",
    "zippo lighters",
  ],
  competition: [
    "air hockey",
    "animal fancy",
    "antakshari",
    "axe throwing",
    "backgammon",
    "barbecue competition",
    "beauty pageants",
    "bell ring competitions",
    "bicycle racing",
    "billiards",
    "bingo",
    "bobsled racing",
    "boating races",
    "board games",
    "brain teasers",
    "bridge",
    "bungeed-up driving",
    "bungy competitions",
    "capoeira",
    "card games",
    "cheerleading competitions",
    "chess boxing",
    "climbing competitions",
    "collecting contests",
    "comedy contests",
    "costume contests",
    "counterstrikes",
    "crossword tournaments",
    "cricket",
    "cultural dancing contests",
    "cup stacking",
    "cooking contests",
    "curling competitions",
    "cycling races",
    "debate club",
    "demolition derby",
    "dice games",
    "disco dancing contests",
    "dragon boat racing",
    "drifting contests",
    "drone racing",
    "drum-off contests",
    "duathlon",
    "eating contests",
    "election forecasting contests",
    "electronic music battles",
    "equestrian competitions",
    "escape rooms",
    "esports tournaments",
    "experimental cooking",
    "fashion shows",
    "fencing",
    "field hockey",
    "figure skating competitions",
    "fishing derbies",
    "flag football",
    "frisbee golf",
    "gaming tournaments",
    "garden shows",
    "golf tournaments",
    "go-karting races",
    "gymnastics competitions",
    "hackathons",
    "hacking contests",
    "high jump competitions",
    "horse riding competitions",
    "hot dog eating",
    "ice hockey",
    "ice skating competitions",
    "improvisation contests",
    "ink drawing contests",
    "karaoke contests",
    "knowledge competitions",
    "knife throwing contests",
    "knitting bees",
    "laser tag",
    "lego contests",
    "liquid eating contests",
    "long jump competitions",
    "ludo tournaments",
    "marathon",
    "marble racing",
    "memory championship",
    "mini golf tournaments",
    "model racing",
    "model rocket competitions",
    "mixed martial arts",
    "motor racing",
    "mountain biking races",
    "multiplayer gaming",
    "musical chairs",
    "mustache contests",
    "netball tournaments",
    "news reading contests",
    "object stacking",
    "orienteering races",
    "outside adventure races",
    "paintball",
    "pole dancing competitions",
    "poker",
    "pool tournaments",
    "puzzles competitions",
    "quiz bowl",
    "quiz night",
    "race walking",
    "rally racing",
    "ring toss",
    "role playing games",
    "rodeo",
    "rugby league football",
    "rugby union football",
    "rummicup tournaments",
    "running races",
    "salsa dance-offs",
    "samba dance-off",
    "saucer catching contest",
    "scale modeling contests",
    "scavenger hunts",
    "scooter races",
    "shooting sports",
    "shuffleboard",
    "silly walks competition",
    "skating competitions",
    "skateboarding contests",
    "skiing competitions",
    "snooker tournaments",
    "soapbox derby",
    "soccer",
    "softball tournaments",
    "spelling bee",
    "speedcubing",
    "sport stacking",
    "square dancing competitions",
    "table tennis",
    "taste testing competitions",
    "taekwondo",
    "teacup derby",
    "team sports competitions",
    "television game shows",
    "tennis",
    "trail running races",
    "trading card games",
    "trampoline competitions",
    "triathlon",
    "ultimate frisbee",
    "underwater hockey",
    "utility belt competitions",
    "volleyball",
    "water polo",
    "welding contests",
    "weightlifting",
    "whisky tasting contests",
    "wolf calling contests",
    "word games",
    "wrestling",
    "yarn spinning contests",
    "yo-yo contests",
    "zumba classes competition",
  ],
  observation: [
    "amateur astronomy",
    "audiophile listening",
    "birdwatching",
    "butterfly watching",
    "cloud watching",
    "dawn watching",
    "fishkeeping observation",
    "foliage watching",
    "movie watching",
    "people watching",
    "plant identification",
    "rainbow spotting",
    "satellite watching",
    "sky watching",
    "sunrise watching",
    "sunset watching",
    "weather watching",
    "whale watching",
  ],
};

export default function searchEngineHobbie(
  category:
    | "general"
    | "sports_and_outdoors"
    | "education"
    | "collection"
    | "competition"
    | "observation",
  query: string,
): string[] {
  const list = hobbies[category] || [];

  if (!query) return list;

  const filtered = hobbies[category].filter((item) =>
    item.toLowerCase().includes(query.toLowerCase()),
  );

  const formatted = filtered.map(
    (item) => item.charAt(0).toUpperCase() + item.slice(1),
  );

  return formatted;
}
