export const professions = [
  "Academic Advisor",
  "Accountant",
  "Acrobat",
  "Actor/Actress",
  "Actuary",
  "Acupuncturist",
  "Administrator",
  "Aerospace Engineer",
  "Air Traffic Controller",
  "Alchemist",
  "Ambassador",
  "Analyst",
  "Anesthetist",
  "Anesthesiologist",
  "Anchorman",
  "Animator",
  "Animal Trainer",
  "Announcer",
  "Antique Dealer",
  "Arborist",
  "Archaeologist",
  "Archbishop",
  "Architect",
  "Archivist",
  "Arborist",
  "Archivist",
  "Art Dealer",
  "Art Director",
  "Artist",
  "Assayer",
  "Assessor",
  "Assistant",
  "Astrologer",
  "Astronaut",
  "Astronomer",
  "Astrophysicist",
  "Athlete",
  "Athletic Trainer",
  "Attorney",
  "Auctioneer",
  "Author",
  "Automobile Racer",
  "Automotive Designer",
  "Audiologist",
  "Auditor",
  "Audio Analyser",
  "Babysitter",
  "Bacteriologist",
  "Bailiff",
  "Baker",
  "Balloonist",
  "Bank Teller",
  "Banker",
  "Bar Keeper",
  "Barber",
  "Bargeman",
  "Barista",
  "Barman",
  "Barrister",
  "Bartender",
  "Bassoonist",
  "Batman",
  "Beautician",
  "Beauty Specialist",
  "Beauty Therapist",
  "Beekeeper",
  "Bellhop",
  "Biographer",
  "Biologist",
  "Bishop",
  "Blacksmith",
  "Boatman",
  "Bodyguard",
  "Boilermaker",
  "Bookbinder",
  "Bookkeeper",
  "Bookseller",
  "Border Patrol Police Officer",
  "Bounty Hunter",
  "Boxer",
  "Brain Surgeon",
  "Brewer",
  "Bricklayer",
  "Broker",
  "Builder",
  "Bureaucrat",
  "Butcher",
  "Butler",
  "Cab Driver",
  "Cabinetmaker",
  "Caddy",
  "Calligrapher",
  "Cameraman",
  "Captain",
  "Cardinal",
  "Cardiologist",
  "Carpenter",
  "Cartoonist",
  "Cartographer",
  "Cashier",
  "Cellist",
  "Chancellor",
  "Chaplain",
  "Chauffeur",
  "Chess Player",
  "Cheesemaker",
  "Chef",
  "Chemist",
  "Chief Compliance Officer",
  "Chief Engineer",
  "Chief Executive Officer",
  "Chief Financial Officer",
  "Chief Information Officer",
  "Chief Of Police",
  "Chief Privacy Officer",
  "Chief Technology Officer",
  "Chimney Sweep",
  "Chiropodist",
  "Chiropractor",
  "Choreographer",
  "Cinematographer",
  "Civil Servant",
  "Civil Engineer",
  "Clarinetist",
  "Cleaner",
  "Clergyman",
  "Clerk",
  "Climatologist",
  "Clockmaker",
  "Clown",
  "Coach",
  "Coachman",
  "Coast Guard",
  "Cobbler",
  "Columnist",
  "Comedian",
  "Company Secretary",
  "Compassmith",
  "Composer",
  "Computer Programmer",
  "Conductor (Music)",
  "Conductor (Transportation)",
  "Confectioner",
  "Conferencier",
  "Constable",
  "Cooper",
  "Construction Engineer",
  "Construction Foreman",
  "Construction Worker",
  "Consul",
  "Consultant",
  "Controller",
  "Copywriter",
  "Coroner",
  "Corrections Officer",
  "Corresponder",
  "Cosmetologist",
  "Cosmonaut",
  "Costume Designer",
  "Courier",
  "Court Jester",
  "Cowboy",
  "Crafter",
  "Crammer",
  "Cryptographer",
  "Cryptozoologist",
  "Curator",
  "Currier",
  "Custodian",
  "Customer Service Representative",
  "Customs Officer",
  "Cyclist",
  "Dancer",
  "Dealer",
  "Delivery Man",
  "Dental Hygienist",
  "Dentist",
  "Deputy (Law Enforcement)",
  "Dermatologist",
  "Demolitionist",
  "Designer",
  "Detective",
  "Dietician",
  "Diplomat",
  "Disc Jockey",
  "Dispatcher",
  "Diver",
  "Dock Labourer",
  "Doctor",
  "Documentalist",
  "Dog Walker",
  "Doorman",
  "Dramatist",
  "Dressmaker",
  "Dressman",
  "Driver",
  "Drummer",
  "DJ",
  "Ecologist",
  "Editor",
  "Educationalist",
  "Electrical Engineer",
  "Electrician",
  "Embalmer",
  "Engine Driver",
  "Engine Fitter",
  "Engineer",
  "Entertainer",
  "Entrepreneur",
  "Environmental Engineer",
  "Environmental Scientist",
  "Estate Agent",
  "Ethnologist",
  "Ethologist",
  "Etymologist",
  "Evangelist",
  "Examiner",
  "Executive",
  "Executor",
  "Explorer",
  "Executioner",
  "Factory Worker",
  "Falconer",
  "Farmer",
  "Farrier",
  "Fashion Designer",
  "Ferryman",
  "Film Critic",
  "Film Director",
  "Film Producer",
  "Financial Adviser",
  "Financial Analyst",
  "Fire Marshal",
  "Firefighter",
  "First Mate",
  "Fisherman",
  "Fishmonger",
  "Fishwife",
  "Fitter",
  "Flautist",
  "Flavorist",
  "Fletcher",
  "Flight Attendant",
  "Flight Engineer",
  "Flight Instructor",
  "Flight Technician",
  "Floor Manager",
  "Florist",
  "Flutist",
  "Food Critic",
  "Footballer",
  "Footman",
  "Forester",
  "Fortune Teller",
  "Fowler",
  "Funeral Director",
  "Game Designer",
  "Game Programmer",
  "Game Show Host",
  "Game Warden",
  "Gamekeeper",
  "Gangster",
  "Garbage Collector",
  "Gardener",
  "Gate-Keeper",
  "Gemcutter",
  "Genealogist",
  "General",
  "Geographer",
  "Geologist",
  "Geometrician",
  "Geophysicist",
  "Gigolo",
  "Gladiator",
  "Goldsmith",
  "Gondolier",
  "Gofer",
  "Government Agent",
  "Governor",
  "Grammarian",
  "Graphic Artist",
  "Graphic Designer",
  "Gravedigger",
  "Greengrocer",
  "Grocer",
  "Guard",
  "Guide",
  "Guitarist",
  "Gunsmith",
  "Hairdresser",
  "Hairstylist",
  "Handyman",
  "Harbourmaster",
  "Harpist",
  "Hatter",
  "Headmaster",
  "Headmistress",
  "Health Inspector",
  "Herder",
  "Historian",
  "Homeopath",
  "Hornist",
  "Host",
  "Hostess",
  "Hotel Manager",
  "Hotelier",
  "House Painter",
  "Housekeeper",
  "Housewife",
  "Homeowner",
  "Hunter",
  "Hydraulic Engineer",
  "Ice Cream Vendor",
  "Illuminator",
  "Illusionist",
  "Illustrator",
  "Image Consultant",
  "Imam",
  "Impersonator",
  "Importer",
  "Industrial Engineer",
  "Industrialist",
  "Information Technologist",
  "Information Broker",
  "Inker",
  "Innkeeper",
  "Instructor",
  "Insurance Agent",
  "Intelligence Officer",
  "Intercity Bus Driver",
  "Interior Designer",
  "Internist",
  "Interpreter",
  "Interrogator",
  "Inventor",
  "Investment Banker",
  "Investment Broker",
  "Ironmonger",
  "Ironmaster",
  "Ironworker",
  "Jailer",
  "Janitor",
  "Jeweller",
  "Jockey",
  "Joggler",
  "Joiner",
  "Joker",
  "Journalist",
  "Judge",
  "Juggler",
  "Jurist",
  "Karate Master",
  "Kickboxer",
  "Kindergarten Teacher",
  "Kinesiologist",
  "King",
  "Laboratory Technician",
  "Laborer",
  "Lady-In-Waiting",
  "Landlord",
  "Landlady",
  "Laundry Worker",
  "Law Enforcement Agent",
  "Lawyer",
  "Leadworker",
  "Leatherworker",
  "Leatherer",
  "Lecturer",
  "Legislator",
  "Level Designer",
  "Librarian",
  "Librarianship",
  "Librettist",
  "Lieutenant",
  "Lifeguard",
  "Lighthouse Keeper",
  "Lighting Technician",
  "Lineman",
  "Linguist",
  "Loan Officer",
  "Lobbyist",
  "Locksmith",
  "Logistician",
  "Lumberjack",
  "Lyricist",
  "Magistrate",
  "Magician",
  "Magnate",
  "Maid",
  "Mail Carrier",
  "Make-Up Artist",
  "Management Consultant",
  "Manager",
  "Manicurist",
  "Manservant",
  "Manual Therapist",
  "Manufacturer",
  "Marine Biologist",
  "Marine Engineer",
  "Market Gardener",
  "Marketing Manager",
  "Marksman",
  "Marshal",
  "Martial Artist",
  "Mason",
  "Master Of Business Administration",
  "Master Of Ceremonies",
  "Massage Therapist",
  "Matador",
  "Mathematician",
  "Matron",
  "Mayor",
  "Mechanic",
  "Mechanical Engineer",
  "Mechanician",
  "Mediator",
  "Medical Assistant",
  "Medical Biller",
  "Medical Coder",
  "Medical Laboratory Scientist",
  "Medical Practitioner",
  "Medical Transcriptionist",
  "Mercer",
  "Merchant",
  "Mesmerist",
  "Messenger",
  "Meteorologist",
  "Midwife",
  "Milkmaid",
  "Milkman",
  "Miller",
  "Miner",
  "Minister",
  "Missionary",
  "Mobile Developer",
  "Mobster",
  "Model",
  "Modeller",
  "Moldmaker",
  "Moneychanger",
  "Moneylender",
  "Monk",
  "Moonlighter",
  "Mortgage Broker",
  "Mountaineer",
  "Muralist",
  "Music Educator",
  "Music Director",
  "Musician",
  "Nanny",
  "Navigator",
  "Negotiator",
  "Netmaker",
  "Neurologist",
  "Neuroscientist",
  "News Caster",
  "Night Auditor",
  "Night Watchman",
  "Notary Public",
  "Novelist",
  "Numerologist",
  "Nun",
  "Nurse",
  "Nurse Practitioner",
  "Nutritionist",
  "Oboist",
  "Obstetrician",
  "Oceanographer",
  "Occupational Therapist",
  "Occupational Therapy Assistant",
  "Ocularist",
  "Odontologist",
  "Oenologist",
  "Oncologist",
  "Operator",
  "Ophthalmologist",
  "Optician",
  "Optometrist",
  "Oracle",
  "Ordinary Seaman",
  "Organizer",
  "Orthodontist",
  "Orthopaedic Surgeon",
  "Orthopaedist",
  "Ornithologist",
  "Ostler",
  "Otolaryngologist",
  "Painter",
  "Paleontologist",
  "Paleoseismologist",
  "Paramedic",
  "Park Ranger",
  "Parole Officer",
  "Party Leader",
  "Pastor",
  "Patent Attorney",
  "Patent Examiner",
  "Pathologist",
  "Pawnbroker",
  "Peddler",
  "Pediatrician",
  "Pedologist",
  "Percussionist",
  "Perfumer",
  "Personal Trainer",
  "Pharmacist",
  "Philanthropist",
  "Philologist",
  "Philosopher",
  "Photographer",
  "Photographer Assistant",
  "Physical Therapist",
  "Physician",
  "Physician Assistant",
  "Physicist",
  "Physiognomist",
  "Physiologist",
  "Physiotherapist",
  "Pianist",
  "Piano Tuner",
  "Pilot",
  "Pilot (Shipping)",
  "Pirate",
  "Plasterer",
  "Plumber",
  "Podiatrist",
  "Poet",
  "Poker Player",
  "Pollster",
  "Police Detective",
  "Police Inspector",
  "Police Officer",
  "Politician",
  "Political Scientist",
  "Pool Attendant",
  "Pool Boy",
  "Pope",
  "Porter",
  "Porter",
  "Portuguese Translator",
  "Postmaster",
  "Postman",
  "Potter",
  "Poulterer",
  "Practitioner",
  "Presenter",
  "President",
  "Press Officer",
  "Priest",
  "Principal",
  "Prince",
  "Princess",
  "Printer",
  "Prison Officer",
  "Prisoner",
  "Private Detective",
  "Probation Officer",
  "Proctologist",
  "Producer",
  "Product Designer",
  "Professor",
  "Programmer",
  "Project Manager",
  "Proofreader",
  "Prosecutor",
  "Psychiatrist",
  "Psychodramatist",
  "Psychologist",
  "Psychotherapist",
  "Public Relations Officer",
  "Public Speaker",
  "Publicist",
  "Publisher",
  "Puppeteer",
  "Queen",
  "Queen Consort",
  "Queen Dowager",
  "Queen Mother",
  "Queen Regnant",
  "Quilter",
  "Rabbi",
  "Radiologist",
  "Radiographer",
  "Race Car Driver",
  "Rat Catcher",
  "Real Estate Broker",
  "Real Estate Developer",
  "Real Estate Investor",
  "Receptionist",
  "Record Producer",
  "Referee",
  "Refuse Collector",
  "Registrar",
  "Registered Nurse",
  "Remedial Teacher",
  "Reporter",
  "Researcher",
  "Resource Room Assistant",
  "Respiratory Therapist",
  "Restaurateur",
  "Retail Manager",
  "Retailer",
  "Revolutionary",
  "Rockstar",
  "Sailmaker",
  "Sailor",
  "Sales Director",
  "Sales Manager",
  "Sales Representative",
  "Sanitation Worker",
  "Saraiman",
  "Saucier",
  "Saxophonist",
  "Sawyer",
  "Scientist",
  "Scout Leader",
  "Screenwriter",
  "Scribe",
  "Sculptor",
  "Seamstress",
  "Second Mate",
  "Secret Service Agent",
  "Secretary",
  "Secretary General",
  "Security Guard",
  "Senator",
  "Servant",
  "SEO Specialist",
  "Sexologist",
  "Sexton",
  "Sheepshearer",
  "Sheriff",
  "Sheriff Officer",
  "Shepherd",
  "Shoemaker",
  "Shoeshiner",
  "Signalman",
  "Singer",
  "Skydiver",
  "Sleuth",
  "Sniper",
  "Social Worker",
  "Soil Scientist",
  "Soldier",
  "Solicitor",
  "Sommelier",
  "Sonographer",
  "Sound Engineer",
  "Sound Technician",
  "Special Agent",
  "Speech Therapist",
  "Sports Analyst",
  "Sports Commentator",
  "Sports Manager",
  "Spy",
  "Stage Designer",
  "Statistician",
  "Steersman",
  "Stevedore",
  "Steward",
  "Stewardess",
  "Street Artist",
  "Street Musician",
  "Stock Breeder",
  "Stockbroker",
  "Street Sweeper",
  "Street Vendor",
  "Stripper",
  "Structural Engineer",
  "Student",
  "Stunt Double",
  "Stunt Performer",
  "Stuntman",
  "Suicidologist",
  "Surgeon",
  "Surgeon",
  "Superintendent",
  "Supervisor",
  "Surveyor",
  "Swimmer",
  "Switchboard Operator",
  "Syndic",
  "System Administrator",
  "System Analyst",
  "Systems Designer",
  "Tailor",
  "Taikonaut",
  "Tanner",
  "Tapicer",
  "Tax Collector",
  "Tax Lawyer",
  "Taxidermist",
  "Taxi Driver",
  "Taxonomist",
  "Teacher",
  "Technical Engineer",
  "Technician",
  "Technologist",
  "Technical Writer",
  "Telegraphist",
  "Telephone Operator",
  "Tennis Player",
  "Terminator",
  "Test Developer",
  "Test Pilot",
  "Thatcher",
  "Theatre Director",
  "Theologian",
  "Therapist",
  "Thief",
  "TikToker",
  "Tiler",
  "Toolmaker",
  "Trader",
  "Translator",
  "Treasurer",
  "Tuner",
  "Tutor",
  "Typist",
  "Ufologist",
  "Umbrella Maker",
  "Undercover Agent",
  "Undertaker",
  "Underwear Model",
  "Underwriter",
  "Upholsterer",
  "Urban Planner",
  "Urologist",
  "Usher",
  "Valet",
  "Verger",
  "Ventriloquist",
  "Veterinarian",
  "Vibraphonist",
  "Vicar",
  "Vice President",
  "Victualler",
  "Video Editor",
  "Video Game Developer",
  "Vintner",
  "Violinist",
  "Violist",
  "Voice Actor",
  "Waiter",
  "Waiting Staff",
  "Waste Collector",
  "Watchmaker",
  "Weaponsmith",
  "Weather Reporter",
  "Weaver",
  "Web Coder",
  "Web Designer",
  "Web Developer",
  "Wedding Planner",
  "Welder",
  "Wet Nurse",
  "Wine Taster",
  "Winemaker",
  "Window Dresser",
  "Wireless Operator",
  "Woodcarver",
  "Woodcutter",
  "Wrangler",
  "Wrestler",
  "Writer",
  "Xylophonist",
  "Yodeler",
  "YouTuber",
  "Zookeeper",
  "Zoologist",
];
